# Generated by Django 4.1.3 on 2022-12-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('gas_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('gas_station_name', models.CharField(max_length=15)),
                ('gas_station_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerLicense',
            fields=[
                ('owner_license', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('owner_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_car_registration', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDiagnosis.ownerlicense')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_vin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('car_brand', models.CharField(max_length=10)),
                ('car_type', models.CharField(max_length=10)),
                ('car_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDiagnosis.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('engine_vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carDiagnosis.car')),
                ('engine_code', models.CharField(max_length=10)),
                ('engine_volume', models.FloatField()),
                ('engine_type', models.CharField(max_length=10)),
                ('engine_power', models.IntegerField()),
            ],
            options={
                'unique_together': {('engine_vin', 'engine_code')},
            },
        ),
        migrations.CreateModel(
            name='GasStationCar',
            fields=[
                ('gas_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carDiagnosis.gasstation')),
                ('by_whom', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=8)),
                ('amount_of_fuel', models.IntegerField()),
                ('car_vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDiagnosis.car')),
            ],
            options={
                'unique_together': {('gas_station_id', 'car_vin')},
            },
        ),
    ]
